export const AIRPORTS = [
  // Europe
  { iata: 'LHR', name: 'Heathrow', city: 'London', country: 'UK' },
  { iata: 'LGW', name: 'Gatwick', city: 'London', country: 'UK' },
  { iata: 'STN', name: 'Stansted', city: 'London', country: 'UK' },
  { iata: 'CDG', name: 'Charles de Gaulle', city: 'Paris', country: 'France' },
  { iata: 'ORY', name: 'Orly', city: 'Paris', country: 'France' },
  { iata: 'AMS', name: 'Schiphol', city: 'Amsterdam', country: 'Netherlands' },
  { iata: 'FRA', name: 'Frankfurt', city: 'Frankfurt', country: 'Germany' },
  { iata: 'MUC', name: 'Munich', city: 'Munich', country: 'Germany' },
  { iata: 'BER', name: 'Brandenburg', city: 'Berlin', country: 'Germany' },
  { iata: 'HAM', name: 'Hamburg', city: 'Hamburg', country: 'Germany' },
  { iata: 'MAD', name: 'Barajas', city: 'Madrid', country: 'Spain' },
  { iata: 'BCN', name: 'El Prat', city: 'Barcelona', country: 'Spain' },
  { iata: 'AGP', name: 'Costa del Sol', city: 'Málaga', country: 'Spain' },
  { iata: 'PMI', name: 'Son Sant Joan', city: 'Palma de Mallorca', country: 'Spain' },
  { iata: 'FCO', name: 'Fiumicino', city: 'Rome', country: 'Italy' },
  { iata: 'MXP', name: 'Malpensa', city: 'Milan', country: 'Italy' },
  { iata: 'VCE', name: 'Marco Polo', city: 'Venice', country: 'Italy' },
  { iata: 'NAP', name: 'Capodichino', city: 'Naples', country: 'Italy' },
  { iata: 'ZRH', name: 'Zurich', city: 'Zurich', country: 'Switzerland' },
  { iata: 'GVA', name: 'Geneva', city: 'Geneva', country: 'Switzerland' },
  { iata: 'VIE', name: 'Vienna', city: 'Vienna', country: 'Austria' },
  { iata: 'CPH', name: 'Kastrup', city: 'Copenhagen', country: 'Denmark' },
  { iata: 'ARN', name: 'Arlanda', city: 'Stockholm', country: 'Sweden' },
  { iata: 'GOT', name: 'Landvetter', city: 'Gothenburg', country: 'Sweden' },
  { iata: 'MMX', name: 'Sturup', city: 'Malmö', country: 'Sweden' },
  { iata: 'OSL', name: 'Gardermoen', city: 'Oslo', country: 'Norway' },
  { iata: 'BGO', name: 'Flesland', city: 'Bergen', country: 'Norway' },
  { iata: 'HEL', name: 'Helsinki-Vantaa', city: 'Helsinki', country: 'Finland' },
  { iata: 'LIS', name: 'Humberto Delgado', city: 'Lisbon', country: 'Portugal' },
  { iata: 'OPO', name: 'Francisco Sá Carneiro', city: 'Porto', country: 'Portugal' },
  { iata: 'ATH', name: 'Eleftherios Venizelos', city: 'Athens', country: 'Greece' },
  { iata: 'HER', name: 'Nikos Kazantzakis', city: 'Heraklion', country: 'Greece' },
  { iata: 'SKG', name: 'Macedonia', city: 'Thessaloniki', country: 'Greece' },
  { iata: 'BRU', name: 'Brussels', city: 'Brussels', country: 'Belgium' },
  { iata: 'DUB', name: 'Dublin', city: 'Dublin', country: 'Ireland' },
  { iata: 'WAW', name: 'Chopin', city: 'Warsaw', country: 'Poland' },
  { iata: 'KRK', name: 'John Paul II', city: 'Krakow', country: 'Poland' },
  { iata: 'PRG', name: 'Václav Havel', city: 'Prague', country: 'Czech Republic' },
  { iata: 'BUD', name: 'Budapest', city: 'Budapest', country: 'Hungary' },
  { iata: 'RIX', name: 'Riga', city: 'Riga', country: 'Latvia' },
  { iata: 'TLL', name: 'Lennart Meri', city: 'Tallinn', country: 'Estonia' },
  { iata: 'VNO', name: 'Vilnius', city: 'Vilnius', country: 'Lithuania' },
  { iata: 'IST', name: 'Istanbul', city: 'Istanbul', country: 'Turkey' },
  { iata: 'SAW', name: 'Sabiha Gökçen', city: 'Istanbul', country: 'Turkey' },
  { iata: 'AYT', name: 'Antalya', city: 'Antalya', country: 'Turkey' },
  { iata: 'TLV', name: 'Ben Gurion', city: 'Tel Aviv', country: 'Israel' },
  { iata: 'OTP', name: 'Henri Coandă', city: 'Bucharest', country: 'Romania' },
  { iata: 'SOF', name: 'Sofia', city: 'Sofia', country: 'Bulgaria' },
  { iata: 'BEG', name: 'Nikola Tesla', city: 'Belgrade', country: 'Serbia' },
  { iata: 'ZAG', name: 'Franjo Tuđman', city: 'Zagreb', country: 'Croatia' },
  { iata: 'DBV', name: 'Dubrovnik', city: 'Dubrovnik', country: 'Croatia' },
  { iata: 'SPU', name: 'Split', city: 'Split', country: 'Croatia' },
  { iata: 'SVO', name: 'Sheremetyevo', city: 'Moscow', country: 'Russia' },
  { iata: 'LED', name: 'Pulkovo', city: 'St Petersburg', country: 'Russia' },
  // North America
  { iata: 'JFK', name: 'John F. Kennedy', city: 'New York', country: 'USA' },
  { iata: 'LGA', name: 'LaGuardia', city: 'New York', country: 'USA' },
  { iata: 'EWR', name: 'Newark', city: 'New York', country: 'USA' },
  { iata: 'LAX', name: 'Los Angeles', city: 'Los Angeles', country: 'USA' },
  { iata: 'SFO', name: 'San Francisco', city: 'San Francisco', country: 'USA' },
  { iata: 'ORD', name: "O'Hare", city: 'Chicago', country: 'USA' },
  { iata: 'MDW', name: 'Midway', city: 'Chicago', country: 'USA' },
  { iata: 'MIA', name: 'Miami', city: 'Miami', country: 'USA' },
  { iata: 'ATL', name: 'Hartsfield-Jackson', city: 'Atlanta', country: 'USA' },
  { iata: 'DFW', name: 'Dallas Fort Worth', city: 'Dallas', country: 'USA' },
  { iata: 'DEN', name: 'Denver', city: 'Denver', country: 'USA' },
  { iata: 'SEA', name: 'Sea-Tac', city: 'Seattle', country: 'USA' },
  { iata: 'BOS', name: 'Logan', city: 'Boston', country: 'USA' },
  { iata: 'LAS', name: 'Harry Reid', city: 'Las Vegas', country: 'USA' },
  { iata: 'PHX', name: 'Sky Harbor', city: 'Phoenix', country: 'USA' },
  { iata: 'IAH', name: 'George Bush', city: 'Houston', country: 'USA' },
  { iata: 'MSP', name: 'Minneapolis', city: 'Minneapolis', country: 'USA' },
  { iata: 'DTW', name: 'Detroit Metro', city: 'Detroit', country: 'USA' },
  { iata: 'PHL', name: 'Philadelphia', city: 'Philadelphia', country: 'USA' },
  { iata: 'CLT', name: 'Charlotte Douglas', city: 'Charlotte', country: 'USA' },
  { iata: 'MCO', name: 'Orlando', city: 'Orlando', country: 'USA' },
  { iata: 'YYZ', name: 'Pearson', city: 'Toronto', country: 'Canada' },
  { iata: 'YVR', name: 'Vancouver', city: 'Vancouver', country: 'Canada' },
  { iata: 'YUL', name: 'Montréal-Trudeau', city: 'Montreal', country: 'Canada' },
  { iata: 'YYC', name: 'Calgary', city: 'Calgary', country: 'Canada' },
  { iata: 'MEX', name: 'Benito Juárez', city: 'Mexico City', country: 'Mexico' },
  { iata: 'CUN', name: 'Cancún', city: 'Cancún', country: 'Mexico' },
  { iata: 'GDL', name: 'Miguel Hidalgo', city: 'Guadalajara', country: 'Mexico' },
  { iata: 'PTY', name: 'Tocumen', city: 'Panama City', country: 'Panama' },
  { iata: 'SJU', name: 'Luis Muñoz Marín', city: 'San Juan', country: 'Puerto Rico' },
  // South America
  { iata: 'GRU', name: 'Guarulhos', city: 'São Paulo', country: 'Brazil' },
  { iata: 'GIG', name: 'Galeão', city: 'Rio de Janeiro', country: 'Brazil' },
  { iata: 'BSB', name: 'Brasília', city: 'Brasília', country: 'Brazil' },
  { iata: 'BOG', name: 'El Dorado', city: 'Bogotá', country: 'Colombia' },
  { iata: 'MDE', name: 'José María Córdova', city: 'Medellín', country: 'Colombia' },
  { iata: 'LIM', name: 'Jorge Chávez', city: 'Lima', country: 'Peru' },
  { iata: 'EZE', name: 'Ministro Pistarini', city: 'Buenos Aires', country: 'Argentina' },
  { iata: 'SCL', name: 'Arturo Merino Benítez', city: 'Santiago', country: 'Chile' },
  { iata: 'UIO', name: 'Mariscal Sucre', city: 'Quito', country: 'Ecuador' },
  { iata: 'MVD', name: 'Carrasco', city: 'Montevideo', country: 'Uruguay' },
  // Asia
  { iata: 'DXB', name: 'Dubai', city: 'Dubai', country: 'UAE' },
  { iata: 'AUH', name: 'Abu Dhabi', city: 'Abu Dhabi', country: 'UAE' },
  { iata: 'DOH', name: 'Hamad', city: 'Doha', country: 'Qatar' },
  { iata: 'BKK', name: 'Suvarnabhumi', city: 'Bangkok', country: 'Thailand' },
  { iata: 'DMK', name: 'Don Mueang', city: 'Bangkok', country: 'Thailand' },
  { iata: 'HKT', name: 'Phuket', city: 'Phuket', country: 'Thailand' },
  { iata: 'CNX', name: 'Chiang Mai', city: 'Chiang Mai', country: 'Thailand' },
  { iata: 'NRT', name: 'Narita', city: 'Tokyo', country: 'Japan' },
  { iata: 'HND', name: 'Haneda', city: 'Tokyo', country: 'Japan' },
  { iata: 'KIX', name: 'Kansai', city: 'Osaka', country: 'Japan' },
  { iata: 'SIN', name: 'Changi', city: 'Singapore', country: 'Singapore' },
  { iata: 'HKG', name: 'Hong Kong', city: 'Hong Kong', country: 'China' },
  { iata: 'PEK', name: 'Capital', city: 'Beijing', country: 'China' },
  { iata: 'PVG', name: 'Pudong', city: 'Shanghai', country: 'China' },
  { iata: 'CAN', name: 'Baiyun', city: 'Guangzhou', country: 'China' },
  { iata: 'ICN', name: 'Incheon', city: 'Seoul', country: 'South Korea' },
  { iata: 'KUL', name: 'Kuala Lumpur', city: 'Kuala Lumpur', country: 'Malaysia' },
  { iata: 'DEL', name: 'Indira Gandhi', city: 'Delhi', country: 'India' },
  { iata: 'BOM', name: 'Chhatrapati Shivaji', city: 'Mumbai', country: 'India' },
  { iata: 'BLR', name: 'Kempegowda', city: 'Bangalore', country: 'India' },
  { iata: 'MAA', name: 'Chennai', city: 'Chennai', country: 'India' },
  { iata: 'CGK', name: 'Soekarno-Hatta', city: 'Jakarta', country: 'Indonesia' },
  { iata: 'DPS', name: 'Ngurah Rai', city: 'Bali', country: 'Indonesia' },
  { iata: 'MNL', name: 'Ninoy Aquino', city: 'Manila', country: 'Philippines' },
  { iata: 'SGN', name: 'Tan Son Nhat', city: 'Ho Chi Minh City', country: 'Vietnam' },
  { iata: 'HAN', name: 'Noi Bai', city: 'Hanoi', country: 'Vietnam' },
  { iata: 'DAD', name: 'Da Nang', city: 'Da Nang', country: 'Vietnam' },
  { iata: 'KTM', name: 'Tribhuvan', city: 'Kathmandu', country: 'Nepal' },
  { iata: 'CMB', name: 'Bandaranaike', city: 'Colombo', country: 'Sri Lanka' },
  { iata: 'AMM', name: 'Queen Alia', city: 'Amman', country: 'Jordan' },
  { iata: 'MCT', name: 'Muscat', city: 'Muscat', country: 'Oman' },
  { iata: 'RUH', name: 'King Khalid', city: 'Riyadh', country: 'Saudi Arabia' },
  { iata: 'JED', name: 'King Abdulaziz', city: 'Jeddah', country: 'Saudi Arabia' },
  { iata: 'KWI', name: 'Kuwait', city: 'Kuwait City', country: 'Kuwait' },
  { iata: 'BAH', name: 'Bahrain', city: 'Manama', country: 'Bahrain' },
  // Africa
  { iata: 'JNB', name: 'O.R. Tambo', city: 'Johannesburg', country: 'South Africa' },
  { iata: 'CPT', name: 'Cape Town', city: 'Cape Town', country: 'South Africa' },
  { iata: 'CAI', name: 'Cairo', city: 'Cairo', country: 'Egypt' },
  { iata: 'HRG', name: 'Hurghada', city: 'Hurghada', country: 'Egypt' },
  { iata: 'SSH', name: 'Sharm el-Sheikh', city: 'Sharm el-Sheikh', country: 'Egypt' },
  { iata: 'CMN', name: 'Mohammed V', city: 'Casablanca', country: 'Morocco' },
  { iata: 'RAK', name: 'Marrakech-Menara', city: 'Marrakech', country: 'Morocco' },
  { iata: 'TUN', name: 'Carthage', city: 'Tunis', country: 'Tunisia' },
  { iata: 'NBO', name: 'Jomo Kenyatta', city: 'Nairobi', country: 'Kenya' },
  { iata: 'MBA', name: 'Mombasa', city: 'Mombasa', country: 'Kenya' },
  { iata: 'JRO', name: 'Kilimanjaro', city: 'Kilimanjaro', country: 'Tanzania' },
  { iata: 'ZNZ', name: 'Abeid Amani Karume', city: 'Zanzibar', country: 'Tanzania' },
  { iata: 'LOS', name: 'Murtala Muhammed', city: 'Lagos', country: 'Nigeria' },
  { iata: 'ACC', name: 'Kotoka', city: 'Accra', country: 'Ghana' },
  { iata: 'ADD', name: 'Bole', city: 'Addis Ababa', country: 'Ethiopia' },
  { iata: 'MRU', name: 'Sir Seewoosagur Ramgoolam', city: 'Mauritius', country: 'Mauritius' },
  { iata: 'SEZ', name: 'Seychelles', city: 'Mahé', country: 'Seychelles' },
  // Oceania
  { iata: 'SYD', name: 'Kingsford Smith', city: 'Sydney', country: 'Australia' },
  { iata: 'MEL', name: 'Melbourne', city: 'Melbourne', country: 'Australia' },
  { iata: 'BNE', name: 'Brisbane', city: 'Brisbane', country: 'Australia' },
  { iata: 'PER', name: 'Perth', city: 'Perth', country: 'Australia' },
  { iata: 'ADL', name: 'Adelaide', city: 'Adelaide', country: 'Australia' },
  { iata: 'AKL', name: 'Auckland', city: 'Auckland', country: 'New Zealand' },
  { iata: 'CHC', name: 'Christchurch', city: 'Christchurch', country: 'New Zealand' },
  { iata: 'WLG', name: 'Wellington', city: 'Wellington', country: 'New Zealand' },
  { iata: 'NAN', name: 'Nadi', city: 'Nadi', country: 'Fiji' },
  // Antarctica
  { iata: 'USH', name: 'Malvinas Argentinas', city: 'Ushuaia', country: 'Argentina' },
] as const;

export type Airport = typeof AIRPORTS[number];
